/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c VpnIfAdaptor -a VpnIfAdaptor.h:VpnIfAdaptor.cpp ../net.pocentek.vpn.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef VPNIFADAPTOR_H_1351949667
#define VPNIFADAPTOR_H_1351949667

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface net.pocentek.vpn
 */
class VpnIfAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "net.pocentek.vpn")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"net.pocentek.vpn\">\n"
"    <method name=\"Status\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"status\"/>\n"
"    </method>\n"
"    <method name=\"Start\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"ret\"/>\n"
"    </method>\n"
"    <method name=\"Stop\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"ret\"/>\n"
"    </method>\n"
"    <signal name=\"StateChanged\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"state\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    VpnIfAdaptor(QObject *parent);
    virtual ~VpnIfAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool Start(const QString &name);
    QVariantMap Status();
    bool Stop(const QString &name);
Q_SIGNALS: // SIGNALS
    void StateChanged(const QString &name, bool state);
};

#endif
