/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c VpnIfAdaptor -a VpnIfAdaptor.h:VpnIfAdaptor.cpp ../net.pocentek.vpn.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "VpnIfAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class VpnIfAdaptor
 */

VpnIfAdaptor::VpnIfAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

VpnIfAdaptor::~VpnIfAdaptor()
{
    // destructor
}

bool VpnIfAdaptor::Start(const QString &name)
{
    // handle method call net.pocentek.vpn.Start
    bool ret;
    QMetaObject::invokeMethod(parent(), "Start", Q_RETURN_ARG(bool, ret), Q_ARG(QString, name));
    return ret;
}

QVariantMap VpnIfAdaptor::Status()
{
    // handle method call net.pocentek.vpn.Status
    QVariantMap status;
    QMetaObject::invokeMethod(parent(), "Status", Q_RETURN_ARG(QVariantMap, status));
    return status;
}

bool VpnIfAdaptor::Stop(const QString &name)
{
    // handle method call net.pocentek.vpn.Stop
    bool ret;
    QMetaObject::invokeMethod(parent(), "Stop", Q_RETURN_ARG(bool, ret), Q_ARG(QString, name));
    return ret;
}

